---
- name: Another network playbook exanple
  # The line below uses regex to parse the inventory file
  hosts: ~^arista
  # gather_facts ALWAYS runs setup.py (server module)
  gather_facts: no # v2.5=< no is default if network_cli is selected for connection
                   # if turned to yes you'll collect info about the local host :(
  
  vars:
    switchint: 13
    switchver: "4.17"

  tasks:
  # if we run this and have gather_facts set to no, then ansible+facts will be about our network devs
    - name: Harvest Arista facts
      eos_facts:
      when: ansible_network_os == "eos"

    - name: Push to the local system -- by special tag request only
      copy: 
        # use the to_no_json filter to display pretty json output
        content: "{{ ansible_facts | to_nic_json }}"
        dest: "~/mycode/{{ inventory_hostname }}.txt"
        # the inventory_hostname variable always resolves to the current host being interated against
      tags: 
        - never
        - grabfacts

        # Precheck conditional number of interfaces
    - fail: 
        msg: "FAIL. Network device lacks the correct number of interfaces."
      when: ansible_facts.net_interfaces|length != switchint

        # Firmware precheck on correctmajhor and minor versions
    - fail:
        msg: "FAIL. Network device is running the wrong firmware."
      when: "switchver not in ansible_facts.net_version"
